#!/usr/bin/env bash
# Transfer a file to my server
# path_to_file=$1
# ip=$2
# username=$3
# path_to_sshKey=$4

if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/
fi
