#!/usr/bin/env bash
# To install nginx and configure it on a remote server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html
sudo nginx -t
sudo service nginx reload
