#!/usr/bin/env bash
# To install nginx and configure it on a remote server

# Update package index
sudo apt-get update

# Install Nginx
sudo apt-get -y install nginx

# Set Nginx to listen on port 80
sudo sed -i 's/^\(.*listen 80;\)$/# \1\nlisten 80;/g' /etc/nginx/sites-available/default
ufw allow 'Nginx HTTP'

# Reload Nginx configuration
sudo nginx -s reload

# Create a basic HTML file with "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Ensure Nginx is running
sudo service nginx restart
