#!/usr/bin/env bash
# backup and compress my databases

# Get the current date for the archive name
current_date=$(date +"%d-%m-%Y")

# MySQL dump file name
dump_file="backup.sql"

# Compressed archive name
archive_name="$current_date.tar.gz"

# MySQL dump command
mysqldump --all-databases -u root --password="$1" > "$dump_file"

# Compress the dump file into a tar.gz archive
tar -czvf "$archive_name" "$dump_file"
