#!/usr/bin/env bash
# installing ufw and blocking all incoming traffic

sudo apt-get update
sudo apt-get install ufw -y

# Block all incoming traffic by default
sudo ufw default deny incoming

# Allow neccessary port
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
